dist: trusty
sudo: required
language: php

php:
  - '7.0'

services:
  - postgresql
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -f examples/localization.sql travis_ci_test
  - composer install --prefer-source --no-interaction
  - ./start_mock_server.sh && SERVER_PID=$!

after_script:
  - kill $SERVER_PID

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.clover --configuration phpunit.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
